version: "3"
services:
  sfLocal:
    image: amazon/aws-stepfunctions-local
    environment:
      AWS_ACCOUNT_ID: 101010101010
      AWS_DEFAULT_REGION: us-east-1
      LAMBDA_ENDPOINT: http://host.docker.internal:4000
    ports:
      - "8083:8083"
  elasticmq:
    image: softwaremill/elasticmq-native
    container_name: 'sls-elasticmq'
    ports:
        - 9324:9324
        - 9325:9325
    volumes:
        - ./elasticmq.conf:/opt/elasticmq.conf
    networks:
        - queuenetwork
networks:
  app:
  queuenetwork:
    driver: bridge
