version: "3"
services:
  dynamodb-local:
    image: "amazon/dynamodb-local"
    ports:
      - "8001:8001"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
  sfLocal:
    image: amazon/aws-stepfunctions-local
    environment:
      AWS_ACCOUNT_ID: 101010101010
      AWS_DEFAULT_REGION: us-east-1
      LAMBDA_ENDPOINT: http://host.docker.internal:4000
    ports:
      - "8083:8083"
networks:
  app:
