service: ${env:APP_NAME, 'tshExampleApp'}
useDotenv: true
plugins:
  - serverless-step-functions-local
  - serverless-step-functions
  - serverless-webpack
  - serverless-dynamodb
  - serverless-offline

package:
  individually: true

custom:
  environment:
    API_KEY: ${env:API_KEY}
  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP_ID}
    subnetIds:
      - ${env:SUBNET_ID_1}
      - ${env:SUBNET_ID_2}
  webpack:
    webpackConfig: "webpack.config.js"
    packager: "npm"
  stepFunctionsLocal:
    externalInstance: true
    accountId: 101010101010
    region: us-east-1
    stepFunctionsEndpoint: http://127.0.0.1:8083
    TaskResourceMapping:
      exampleStep: arn:aws:lambda:us-east-1:101010101010:function:${env:APP_NAME, 'tshExampleApp'}-${opt:stage, 'dev'}-example-step-lambda
      # PLOP_ADD_WORKFLOW_STEP_LOCAL_STEP
  dynamodb:
    stages:
      - local
    start:
      docker: true
      port: 8005
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
  apiKeys:
    local:
      - name: ${env:APP_NAME, 'tshExampleApp'}-local-key
        value: ${env:API_KEY}
    dev:
      - name: ${env:APP_NAME, 'tshExampleApp'}-dev-key

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_LAMBDAS_REGION, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 30
  logRetentionInDays: 30
  environment:
    APP_NAME: ${env:APP_NAME, 'tshExampleApp'}
    AWS_LAMBDAS_REGION: ${env:AWS_LAMBDAS_REGION, 'eu-west-1'}
    API_KEY: ${env:API_KEY}
    DYNAMODB_CURRENCY_TABLE: ${env:APP_NAME, 'tshExampleApp'}-${env:DYNAMODB_CURRENCY_TABLE}-${opt:stage, 'local'}
    CURRENCY_AVAILABLE: ${env:CURRENCY_AVAILABLE}
    CURRENCY_SCOPE: ${env:CURRENCY_SCOPE}
    CURRENCY_API_URL: ${env:CURRENCY_API_URL}
    CURRENCY_API_HEADER: ${env:CURRENCY_API_HEADER}
    CURRENCY_API_TOKEN: ${env:CURRENCY_API_TOKEN}
    RATES_IMPORTER_LAMBDA_RATE: ${env:RATES_IMPORTER_LAMBDA_RATE}
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - ec2:CreateNetworkInterface
          - ec2:DescribeNetworkInterfaces
          - ec2:DeleteNetworkInterface
          - ec2:DetachNetworkInterface
        Resource: "*"
      - Effect: Allow
        Action:
          - lambda:InvokeFunction
          - states:StartExecution
        Resource:
          - "*"
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          Fn::GetAtt:
            - currencyTable
            - Arn
  apiGateway:
    apiKeys: ${self:custom.apiKeys.${opt:stage, 'local'}}

functions:
  - ${file(functions/health-check/function.yml)}
  - ${file(workflows/example-workflow/example-step/function.yml)}
  - ${file(functions/rates-importer/function.yml)}
  # PLOP_ADD_LAMBDA

stepFunctions:
  stateMachines:
  # PLOP_ADD_WORKFLOW_STATE_MACHINE

resources:
  Outputs:
    # PLOP_ADD_WORKFLOW_RESOURCE
  Resources:
    currencyTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${env:APP_NAME, 'tshExampleApp'}-${env:DYNAMODB_CURRENCY_TABLE}-${opt:stage, 'local'}
        AttributeDefinitions:
          - AttributeName: currencyName
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: currencyName
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST